version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=<your_github_token>
      - OPENAI_API_KEY=<your_openai_key>
    depends_on:
      - redis
  redis:
    image: "redis:7.4-alpine"
    ports:
      - "6379:6379"
